# Projektinformationen
site_name: "Nand - RPG"
site_description: "Das Rollenspiel auf dem Mars"
site_author: "hoochicken"
site_url: "http://127.0.0.1:8000"
copyright: "Â© 2025 Mareike Riegel"

# Repository-Infos
repo_name: "GitHub"
repo_url: "https://github.com/hoochicken/nand-rpg/dictionary"
edit_uri: "dictionary/edit/main/docs_sample"

# Dokumentationsverzeichnis
docs_dir: "docs_sample"

# Theme
theme:
  name: material
  language: de
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Wechsel zu hellem Modus
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Wechsel zu dunklem Modus
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

# Plugins
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - de
  - include-markdown

# Markdown-Erweiterungen
markdown_extensions:
  - admonition                 # HOE: Hinweisboxen
  - pymdownx.details           # HOE: aufklappbare Abschnitte
  - pymdownx.superfences       # HOE: verbesserte CodeblÃ¶cke
  - pymdownx.tabbed            # HOE: Reiter/Tabs
  - pymdownx.emoji             # HOE: Emojis wie :rocket:
  - pymdownx.keys              # HOE: Tastenkombis wie âŒ˜+S
  - markdown_include.include:  # HOE: Markdown-Dateien einfÃ¼gen
      base_path: docs_sample

# Eigene Skripte und CSS
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
  - "assets/js/body-quotient-calculator.js"

extra_css:
  - "assets/css/custom.css"

# Weitere Metadaten
extra:
  manifest: "manifest.json"
  page:
    icon: true
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/peaceiris
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/piris314en

# Navigation
nav:
  - ğŸ  Startseite:
    - Einleitung: index.md
    - Nie wieder !: startseite/nie_wieder.md
    - Sound: startseite/sound.md

  - ğŸ§‘â€ğŸš€ Charakter & Regeln:
    - Charaktererstellung: rules/charaktererstellung.md
    - Regeln: rules/regeln.md
    - Spielleiterhilfen: rules/spielleiterhilfen.md
    - Materialsystem: rules/materiallisten.md

  - ğŸ“‹ Spielleiterhilfen:
      - Vorbereitung: rules/spielleiterhilfen.md

  - ğŸª– Kadettschaft:
    - Allgemeine Infos: kadettschaft/allgemein.md
    - Rangabzeichen: kadettschaft/rangabzeichen.md

  - ğŸŒ Weltbeschreibung:
    - Mars: welt/mars.md
    - Bromsal: welt/bromsal.md
    - Zeitlinien: welt/timeline.md
    - Sonnensystem: welt/sonnensystem.md
    - Quantenraum: welt/quantenraum.md
    - Karten: welt/karten.md

  - ğŸ’ AusrÃ¼stung:
    - Ãœbersicht: ausruestung/index.md
    - Geraffel: ausruestung/geraffel.md
    - AnzÃ¼ge: ausruestung/anzuege.md
    - Helme: ausruestung/helme.md
    - Leichtatmer & Handschuhe: ausruestung/leichtatmer-und-handschuhe.md

  - âš™ï¸ Technik:
    - Kommunikation & Medizin:
        - Kommunikation: technik/kommunikation.md
        - Medizin: technik/medizin.md
    - Fahrzeuge & Waffen:
        - Vehikel: technik/vehikel.md
        - Waffen:
          - Granaten: technik/waffen/granaten.md

  - ğŸ§‘â€ğŸŒ¾ Kultur & Alltag:
      - Marser: kultur/marser.md
      - Hobbys: kultur/hobbys.md
      - Kommunikation: kultur/kommunikation.md

  - ğŸ‘½ KrÃ¤fte & VÃ¶lker:
      - VÃ¶lkerÃ¼bersicht: kraefte/voelker.md
      - KI: kraefte/ki.md
      - AKI: kraefte/aki.md
      - Brom: kraefte/brom.md
      - Gott: kraefte/gott.md
      - Raummolche: kraefte/raummolche.md

  - ğŸ² Abenteuer:
      - Hauptkampagne:
          - Wehrerziehungslager: abenteuer/01-wehrerziehungslager.md
          - Der erste Auftrag: abenteuer/02-erster-auftrag.md
          - Stimme aus der Stille: abenteuer/03-stimme-aus-der-stille.md
      - Solo-RPG:
          - Mini-RPG: abenteuer/99-mini-rpg.md
      - NPC-Datenbank:
          - Wehrerziehungslager: npc/wehrerziehungslager.md

  - âš–ï¸ Impressum & Datenschutz: impressum.md
